version: 0.1

phases:
  install:
    runtime-version:
      nodejs: 10
    commands:
      - npm install
      - npm run build-client
      - echo "Installing dependencies"
  build:
    commands:
      - pkg .
      - echo "Build Completed"

artifacts:
  files:
    - 'stock-e-macos'
