version: 0.1

phases:
  install:
    runtime-version:
      nodejs: 10
    commands:
      - npm install
      - npm install -g webpack
      - npm install -g pkg
      - echo "Installing dependencies"
  build:
    commands:
      - echo 'Node Version:'
      - node -v
      - npm run build-client
      - pkg .
      - echo "Build Completed"

artifacts:
  files:
    - 'stock-e-macos'
